import React, { useState, useEffect } from 'react';
import { Trash2, Save, Settings, X } from 'lucide-react';
import DashboardToolbox from './DashboardToolbox';
import DashboardProperties from './DashboardProperties';
import HeadingWidget from './widgets/HeadingWidget';
import MetricWidget from './widgets/MetricWidget';
import ChartWidget from './widgets/ChartWidget';
import { getFeaturesInfo } from '../../api/client';
import { ResponsiveReactGridLayout } from 'react-grid-layout/legacy';

import 'react-grid-layout/css/styles.css';

const DashboardCanvas = ({ 
  isDataLoaded,
  cards,
  setCards,
  layout,
  setLayout,
  anomalyReport
}) => {
  const [widgets, setWidgets] = useState([]);
  const [selectedId, setSelectedId] = useState(null);
  const [columns, setColumns] = useState([]);

  useEffect(() => {
    if (isDataLoaded) fetchCols();
  }, [isDataLoaded]);

  const fetchCols = async () => {
    try {
      const data = await getFeaturesInfo();
      setColumns(data.columns || []);
    } catch (e) {
      console.error(e);
    }
  };

  // Sync widgets with cards & layout from parent props (useful on workspace load/restore)
  useEffect(() => {
    if (cards && cards.length > 0) {
      const reconstructed = cards.map(c => {
        const lay = layout?.find(l => l.i === c.id.toString());
        return {
          id: c.id,
          type: c.type,
          config: c.config,
          x: lay ? lay.x : 0,
          y: lay ? lay.y : 0,
          w: lay ? lay.w : (c.type === 'heading' ? 12 : c.type === 'metric' ? 3 : 6),
          h: lay ? lay.h : (c.type === 'heading' ? 2 : c.type === 'metric' ? 3 : 6)
        };
      });
      // Diff check to prevent update loops
      const hasChanged = reconstructed.length !== widgets.length || 
        reconstructed.some((item, idx) => {
          const w = widgets[idx];
          return !w || w.id !== item.id || w.x !== item.x || w.y !== item.y || w.w !== item.w || w.h !== item.h || JSON.stringify(w.config) !== JSON.stringify(item.config);
        });
      if (hasChanged) {
        setWidgets(reconstructed);
      }
    } else if (widgets.length > 0) {
      setWidgets([]);
    }
  }, [cards, layout]);

  // Helper to update both local state and parent state
  const updateWidgetsStateAndProps = (newWidgets) => {
    setWidgets(newWidgets);
    if (setCards) {
      setCards(newWidgets.map(w => ({ id: w.id, type: w.type, config: w.config })));
    }
    if (setLayout) {
      setLayout(newWidgets.map(w => ({ i: w.id.toString(), x: w.x, y: w.y, w: w.w, h: w.h })));
    }
  };

  const addWidget = (type) => {
    let w, h;
    let config = {};

    if (type === 'heading') {
      w = 12; h = 2;
      config = { text: 'DASHBOARD TITLE', size: 'LARGE', align: 'LEFT' };
    } else if (type === 'metric') {
      w = 3; h = 3;
      config = { column: '', aggregation: 'SUM', label: '', color: '#ffe45e' };
    } else if (type === 'chart') {
      w = 6; h = 6;
      config = { chart_type: 'BAR', x_column: '', y_column: '', aggregation: 'MEAN', title: '', theme: 'BRUTAL', showLegend: true, showGrid: true };
    }

    const newWidget = {
      id: Date.now(),
      type,
      x: 0,
      y: Infinity,
      w,
      h,
      config
    };

    updateWidgetsStateAndProps([...widgets, newWidget]);
    setSelectedId(newWidget.id);
  };

  const updateWidget = (id, updates) => {
    const updated = widgets.map(w => w.id === id ? { ...w, ...updates } : w);
    updateWidgetsStateAndProps(updated);
  };

  const removeWidget = (id) => {
    const updated = widgets.filter(w => w.id !== id);
    updateWidgetsStateAndProps(updated);
    if (selectedId === id) setSelectedId(null);
  };

  const clearCanvas = () => {
    if (window.confirm("Are you sure you want to clear the canvas?")) {
      updateWidgetsStateAndProps([]);
      setSelectedId(null);
    }
  };

  const autoGenerateDashboard = (template, title, metricConfigs, chartConfigs) => {
    const newWidgets = [];
    let currentY = 0;

    // 1. Heading
    if (title) {
      newWidgets.push({
        id: Date.now() + 1,
        type: 'heading',
        x: 0,
        y: currentY,
        w: 12,
        h: 2,
        config: { text: title, size: 'HUGE', align: 'LEFT' }
      });
      currentY += 2;
    }

    // 2. Metrics (Horizontal row)
    let metricCount = 3;
    if (template === 'OVERVIEW') metricCount = 3;
    else if (template === 'DEEP_DIVE') metricCount = 4;
    else if (template === 'COMPARISON') metricCount = 2;

    const metricW = template === 'DEEP_DIVE' ? 3 : (template === 'COMPARISON' ? 6 : 4);
    for (let i = 0; i < metricCount; i++) {
      newWidgets.push({
        id: Date.now() + 10 + i,
        type: 'metric',
        x: i * metricW,
        y: currentY,
        w: metricW,
        h: 3,
        config: { 
          column: metricConfigs[i]?.col || '', 
          aggregation: metricConfigs[i]?.agg || 'SUM', 
          color: ['#ffe45e', '#00f0ff', '#ff499e', '#ff8c00'][i % 4] 
        }
      });
    }
    if (metricCount > 0) currentY += 3;

    // 3. Charts
    let chartCount = 2;
    if (template === 'OVERVIEW') chartCount = 2;
    else if (template === 'DEEP_DIVE') chartCount = 1;
    else if (template === 'COMPARISON') chartCount = 3;

    const chartW = template === 'DEEP_DIVE' ? 12 : (template === 'COMPARISON' ? 4 : 6);
    for (let i = 0; i < chartCount; i++) {
      newWidgets.push({
        id: Date.now() + 100 + i,
        type: 'chart',
        x: i * chartW,
        y: currentY,
        w: chartW,
        h: 6,
        config: { 
          chart_type: chartConfigs[i]?.type || 'BAR', 
          x_column: chartConfigs[i]?.x || '', 
          y_column: chartConfigs[i]?.y || '', 
          aggregation: chartConfigs[i]?.agg || 'MEAN', 
          theme: ['BRUTAL', 'NEON', 'WARM', 'MONO'][i % 4] 
        }
      });
    }

    updateWidgetsStateAndProps(newWidgets);
    setSelectedId(null);
  };

  const handleLayoutChange = (currentLayout) => {
    // Only update coordinates if changed
    const updated = widgets.map(w => {
      const item = currentLayout.find(l => l.i === w.id.toString());
      if (item) {
        return {
          ...w,
          x: item.x,
          y: item.y,
          w: item.w,
          h: item.h
        };
      }
      return w;
    });

    setWidgets(updated);
    if (setCards) {
      setCards(updated.map(w => ({ id: w.id, type: w.type, config: w.config })));
    }
    if (setLayout) {
      setLayout(updated.map(w => ({ i: w.id.toString(), x: w.x, y: w.y, w: w.w, h: w.h })));
    }
  };

  const selectedWidget = widgets.find(w => w.id === selectedId);

  // Generate RGL layout array
  const currentGridLayout = widgets.map(w => ({
    i: w.id.toString(),
    x: w.x,
    y: w.y,
    w: w.w,
    h: w.h,
    minW: w.type === 'heading' ? 4 : w.type === 'metric' ? 2 : 3,
    minH: w.type === 'heading' ? 1 : w.type === 'metric' ? 2 : 3
  }));

  const responsiveLayouts = {
    lg: currentGridLayout,
    md: currentGridLayout,
    sm: currentGridLayout,
    xs: currentGridLayout,
    xxs: currentGridLayout
  };

  return (
    <div className="flex flex-col lg:flex-row w-full h-auto lg:h-[calc(100vh-160px)] min-h-0">
      
      {/* LEFT: TOOLBOX */}
      <DashboardToolbox 
        addWidget={addWidget} 
        autoGenerateDashboard={autoGenerateDashboard} 
        columns={columns} 
      />

      {/* MIDDLE: CANVAS */}
      <div className="flex-1 flex flex-col min-w-0 bg-[#fef9ef] relative">
        
        {/* Canvas Toolbar */}
        <div className="h-[48px] bg-[#fef9ef] border-b-[2px] border-black flex items-center justify-between px-4 shrink-0 z-10">
          <div className="flex gap-2">
            <button 
              onClick={clearCanvas}
              className="px-3 py-1.5 border-[2px] border-black bg-white hover:bg-[#ff499e] hover:text-white transition-colors flex items-center gap-2 font-black uppercase text-xs cursor-pointer"
            >
              <Trash2 size={14} /> Clear Canvas
            </button>
            <button 
              className="px-3 py-1.5 border-[2px] border-black bg-[#ffe45e] hover:bg-yellow-500 transition-colors flex items-center gap-2 font-black uppercase text-xs cursor-pointer"
              onClick={() => alert("Dashboard saved to workspace!")}
            >
              <Save size={14} /> Save Layout
            </button>
          </div>
          <div className="font-black text-[10px] uppercase bg-black text-white px-2 py-1 select-none">
            {widgets.length} WIDGETS
          </div>
        </div>

        {/* Canvas Area with Dot Grid */}
        <div 
          className="flex-1 overflow-auto relative p-4"
          onClick={() => setSelectedId(null)}
          style={{
            backgroundImage: 'radial-gradient(#00000015 2px, transparent 2px)',
            backgroundSize: '24px 24px'
          }}
        >
          {!isDataLoaded && (
            <div className="absolute inset-0 flex items-center justify-center pointer-events-none z-20">
              <span className="font-black text-2xl uppercase opacity-20 text-black">NO DATA LOADED</span>
            </div>
          )}
          
          <div className="w-full h-full relative">
            <ResponsiveReactGridLayout
              className="layout"
              layouts={responsiveLayouts}
              breakpoints={{ lg: 1200, md: 996, sm: 768, xs: 480, xxs: 0 }}
              cols={{ lg: 12, md: 10, sm: 6, xs: 1, xxs: 1 }}
              rowHeight={50}
              onLayoutChange={handleLayoutChange}
              isDraggable={true}
              isResizable={true}
              draggableHandle=".drag-handle"
            >
              {widgets.map(widget => {
                const isSelected = selectedId === widget.id;
                return (
                  <div 
                    key={widget.id.toString()}
                    className={`bg-white border-[2px] ${isSelected ? 'border-[#ffe45e]' : 'border-black'} flex flex-col transition-shadow duration-100 ${isSelected ? 'shadow-[8px_8px_0px_#000] z-20' : 'shadow-[4px_4px_0px_#000]'}`}
                    onClick={(e) => { e.stopPropagation(); setSelectedId(widget.id); }}
                  >
                    {/* Drag Handle Bar */}
                    <div className="drag-handle h-3 bg-black w-full cursor-grab active:cursor-grabbing flex items-center justify-between shrink-0 relative">
                      {/* Controls on hover/select */}
                      <div 
                        className={`absolute top-0 right-0 -mt-3.5 mr-1 flex gap-1 ${isSelected ? 'opacity-100' : 'opacity-0 group-hover:opacity-100'} transition-opacity z-30`}
                        onClick={e => e.stopPropagation()}
                      >
                        <button 
                          onClick={(e) => { e.stopPropagation(); setSelectedId(widget.id); }}
                          className="bg-black text-white p-1 hover:bg-[#ffe45e] hover:text-black border-2 border-black cursor-pointer"
                          title="Settings"
                        >
                          <Settings size={12} strokeWidth={3} />
                        </button>
                        <button 
                          onClick={(e) => { e.stopPropagation(); removeWidget(widget.id); }}
                          className="bg-[#ff499e] text-white p-1 hover:bg-red-600 border-2 border-black cursor-pointer"
                          title="Delete"
                        >
                          <X size={12} strokeWidth={3} />
                        </button>
                      </div>
                    </div>

                    {/* Content */}
                    <div className="flex-1 w-full min-h-0 overflow-hidden relative cursor-default">
                      {widget.type === 'heading' && <HeadingWidget widget={widget} updateWidget={updateWidget} />}
                      {widget.type === 'metric' && <MetricWidget widget={widget} />}
                      {widget.type === 'chart' && <ChartWidget widget={widget} />}
                    </div>
                  </div>
                );
              })}
            </ResponsiveReactGridLayout>
          </div>
        </div>

      </div>

      {/* RIGHT: PROPERTIES */}
      <DashboardProperties 
        selectedWidget={selectedWidget} 
        updateWidget={updateWidget} 
        deselectWidget={() => setSelectedId(null)}
        columns={columns}
      />

    </div>
  );
};

export default DashboardCanvas;
