import React, { useState, useEffect } from 'react';
import { Type, Hash, BarChart2, Sparkles, X, LayoutTemplate, ChevronLeft, ChevronRight } from 'lucide-react';
import { getFeaturesInfo, getFullDataset } from '../../api/client';

const DashboardToolbox = ({ addWidget, autoGenerateDashboard, columns = [] }) => {
  const [showModal, setShowModal] = useState(false);
  const [template, setTemplate] = useState('OVERVIEW'); // OVERVIEW, DEEP_DIVE, COMPARISON
  const [isCollapsed, setIsCollapsed] = useState(false);
  const [modalColumns, setModalColumns] = useState([]);
  
  // States for metric assignments in the modal
  const [metricConfigs, setMetricConfigs] = useState([
    { col: '', agg: 'MEAN' },
    { col: '', agg: 'SUM' },
    { col: '', agg: 'COUNT' },
    { col: '', agg: 'MAX' }
  ]);
  
  // States for chart assignments in the modal
  const [chartConfigs, setChartConfigs] = useState([
    { type: 'BAR', x: '', y: '' },
    { type: 'PIE', x: '', y: '' },
    { type: 'LINE', x: '', y: '' },
    { type: 'SCATTER', x: '', y: '' }
  ]);
  
  const [dashTitle, setDashTitle] = useState('EXECUTIVE SUMMARY');

  const handleGenerate = () => {
    autoGenerateDashboard(template, dashTitle, metricConfigs, chartConfigs);
    setShowModal(false);
  };

  useEffect(() => {
    if (showModal) {
      const fetchModalCols = async () => {
        try {
          const res = await getFeaturesInfo();
          if (res && res.columns) {
            setModalColumns(res.columns);
          } else {
            throw new Error("No columns in features info");
          }
        } catch (err) {
          try {
            const exp = await getFullDataset();
            if (exp && exp.data && exp.data.length > 0) {
              const cols = Object.keys(exp.data[0]).map(k => ({ name: k }));
              setModalColumns(cols);
            }
          } catch (e) {
            console.error("Failed to load columns for modal", e);
          }
        }
      };
      fetchModalCols();
    }
  }, [showModal]);

  if (isCollapsed) {
    return (
      <div 
        className="w-[40px] shrink-0 bg-[#ffe45e] border-r-[3px] border-black flex flex-col items-center py-4 cursor-pointer hover:bg-yellow-400 transition-colors z-10"
        onClick={() => setIsCollapsed(false)}
        title="Expand Toolbox"
      >
        <ChevronRight size={24} strokeWidth={3} className="text-black" />
        <div className="mt-8" style={{ writingMode: 'vertical-rl', transform: 'rotate(180deg)' }}>
          <span className="font-black uppercase tracking-widest text-sm">TOOLBOX</span>
        </div>
      </div>
    );
  }

  return (
    <div className="w-[280px] shrink-0 bg-[#fef9ef] border-r-[3px] border-black flex flex-col h-full z-10 relative transition-all duration-250">
      <div className="p-4 border-b-[3px] border-black shrink-0 bg-white flex justify-between items-center">
        <h2 className="font-black uppercase text-lg tracking-wider">TOOLBOX</h2>
        <button onClick={() => setIsCollapsed(true)} className="hover:text-gray-600 transition-colors">
          <ChevronLeft size={20} strokeWidth={3} />
        </button>
      </div>

      <div className="p-4 space-y-4 flex-1 overflow-y-auto">
        <h3 className="font-black text-xs text-gray-500 uppercase tracking-widest">WIDGETS</h3>
        
        <div 
          onClick={() => addWidget('heading')}
          className="bg-white border-[2px] border-black p-3 cursor-pointer shadow-[4px_4px_0px_#000] hover:-translate-y-1 hover:-translate-x-1 transition-transform flex items-center gap-3"
        >
          <div className="bg-[#ffe45e] p-2 border-2 border-black shrink-0">
            <Type size={20} strokeWidth={3} />
          </div>
          <div>
            <h4 className="font-black text-xs uppercase leading-none">HEADING / TEXT</h4>
            <p className="text-[10px] font-bold text-gray-500 mt-1 uppercase">Add a title or label</p>
          </div>
        </div>

        <div 
          onClick={() => addWidget('metric')}
          className="bg-white border-[2px] border-black p-3 cursor-pointer shadow-[4px_4px_0px_#000] hover:-translate-y-1 hover:-translate-x-1 transition-transform flex items-center gap-3"
        >
          <div className="bg-[#ffe45e] p-2 border-2 border-black shrink-0">
            <Hash size={20} strokeWidth={3} />
          </div>
          <div>
            <h4 className="font-black text-xs uppercase leading-none">METRIC CARD</h4>
            <p className="text-[10px] font-bold text-gray-500 mt-1 uppercase">Display a calculated stat</p>
          </div>
        </div>

        <div 
          onClick={() => addWidget('chart')}
          className="bg-white border-[2px] border-black p-3 cursor-pointer shadow-[4px_4px_0px_#000] hover:-translate-y-1 hover:-translate-x-1 transition-transform flex items-center gap-3"
        >
          <div className="bg-[#ffe45e] p-2 border-2 border-black shrink-0">
            <BarChart2 size={20} strokeWidth={3} />
          </div>
          <div>
            <h4 className="font-black text-xs uppercase leading-none">CHART BLOCK</h4>
            <p className="text-[10px] font-bold text-gray-500 mt-1 uppercase">Visualize your data</p>
          </div>
        </div>

        <div className="pt-6 border-t-[2px] border-black mt-6 space-y-4">
          <div className="flex items-center gap-2">
            <Sparkles size={16} className="text-[#ff8c00]" strokeWidth={3} />
            <h3 className="font-black text-xs text-gray-500 uppercase tracking-widest">AUTO-GENERATE</h3>
          </div>
          
          <button 
            onClick={() => setShowModal(true)}
            className="w-full bg-[#ff8c00] text-white border-[3px] border-black py-3 px-4 font-black uppercase text-sm flex justify-center items-center gap-2 shadow-[6px_6px_0px_#000] hover:-translate-y-1 hover:-translate-x-1 active:translate-x-0 active:translate-y-0 active:shadow-none transition-all"
          >
            ✦ GENERATE DASHBOARD
          </button>
        </div>
      </div>

      {/* AUTO-GENERATE MODAL */}
      {showModal && (
        <div className="fixed inset-0 bg-black/50 z-50 flex items-center justify-center p-4">
          <div className="bg-white border-[3px] border-black shadow-[8px_8px_0px_#000] w-full max-w-2xl max-h-[90vh] flex flex-col">
            
            <div className="bg-black text-white p-4 flex justify-between items-center shrink-0">
              <h3 className="font-black uppercase tracking-wider flex items-center gap-2">
                <Sparkles size={18} /> AUTO-GENERATE DASHBOARD
              </h3>
              <button onClick={() => setShowModal(false)} className="hover:text-[#ff499e] transition-colors">
                <X size={24} strokeWidth={3} />
              </button>
            </div>

            <div className="flex-1 overflow-y-auto p-6 space-y-8 bg-[#fef9ef]">
              
              {/* STEP 1 */}
              <section className="space-y-3">
                <h4 className="font-black text-sm uppercase">STEP 1 — CHOOSE A LAYOUT TEMPLATE</h4>
                <div className="grid grid-cols-3 gap-4">
                  {[
                    { id: 'OVERVIEW', title: 'OVERVIEW', desc: '2 Metrics, 1 Bar, 1 Pie' },
                    { id: 'DEEP_DIVE', title: 'DEEP DIVE', desc: '4 Metrics, 2 Line Charts' },
                    { id: 'COMPARISON', title: 'COMPARISON', desc: '2 Bars, 1 Scatter, 1 Hist' }
                  ].map(t => (
                    <div 
                      key={t.id}
                      onClick={() => setTemplate(t.id)}
                      className={`bg-white border-[3px] p-4 cursor-pointer hover:shadow-[4px_4px_0px_#000] transition-all flex flex-col items-center text-center ${template === t.id ? 'border-[#ffe45e] shadow-[4px_4px_0px_#000] -translate-y-1 -translate-x-1' : 'border-black'}`}
                    >
                      <LayoutTemplate size={32} className="mb-2" strokeWidth={1.5} />
                      <h5 className="font-black text-[10px] uppercase">{t.title}</h5>
                      <p className="text-[9px] font-bold text-gray-500 mt-1 uppercase">{t.desc}</p>
                    </div>
                  ))}
                </div>
              </section>

              {/* STEP 2 */}
              <section className="space-y-3">
                <h4 className="font-black text-sm uppercase">STEP 2 — SELECT YOUR METRICS</h4>
                <div className="grid grid-cols-2 gap-4">
                  {[0, 1, ...(template === 'DEEP_DIVE' ? [2, 3] : [])].map(i => (
                    <div key={i} className="bg-white border-2 border-black p-3 space-y-2">
                      <p className="font-black text-[10px] uppercase text-gray-500 border-b-2 border-gray-100 pb-1">METRIC {i+1}</p>
                      <select 
                        value={metricConfigs[i].col} 
                        onChange={e => {
                          const newConf = [...metricConfigs];
                          newConf[i].col = e.target.value;
                          setMetricConfigs(newConf);
                        }}
                        className="w-full border-[2px] border-black p-1.5 font-bold uppercase text-[10px]"
                      >
                        <option value="">- SELECT COLUMN -</option>
                        {modalColumns.map(c => <option key={c.name} value={c.name}>{c.name}</option>)}
                      </select>
                      <select 
                        value={metricConfigs[i].agg} 
                        onChange={e => {
                          const newConf = [...metricConfigs];
                          newConf[i].agg = e.target.value;
                          setMetricConfigs(newConf);
                        }}
                        className="w-full border-[2px] border-black p-1.5 font-bold uppercase text-[10px]"
                      >
                        {['COUNT', 'SUM', 'MEAN', 'MIN', 'MAX', 'MEDIAN'].map(a => <option key={a} value={a}>{a}</option>)}
                      </select>
                    </div>
                  ))}
                </div>
              </section>

              {/* STEP 3 */}
              <section className="space-y-3">
                <h4 className="font-black text-sm uppercase">STEP 3 — SELECT YOUR CHARTS</h4>
                <div className="grid grid-cols-2 gap-4">
                  {[0, 1, ...(template === 'COMPARISON' ? [2, 3] : [])].map(i => {
                    // pre-select chart type based on template for nice UX
                    const getDefType = () => {
                      if (template === 'OVERVIEW') return i === 0 ? 'BAR' : 'PIE';
                      if (template === 'DEEP_DIVE') return 'LINE';
                      if (template === 'COMPARISON') return ['BAR', 'BAR', 'SCATTER', 'HISTOGRAM'][i];
                      return 'BAR';
                    };
                    
                    return (
                    <div key={i} className="bg-white border-2 border-black p-3 space-y-2">
                      <p className="font-black text-[10px] uppercase text-gray-500 border-b-2 border-gray-100 pb-1 flex justify-between">
                        <span>CHART {i+1}</span>
                      </p>
                      <select 
                        value={chartConfigs[i].type || getDefType()} 
                        onChange={e => {
                          const newConf = [...chartConfigs];
                          newConf[i].type = e.target.value;
                          setChartConfigs(newConf);
                        }}
                        className="w-full border-[2px] border-black p-1.5 font-bold uppercase text-[10px] bg-[#fff5ba]"
                      >
                        {['BAR', 'LINE', 'SCATTER', 'PIE', 'AREA', 'HISTOGRAM'].map(t => <option key={t} value={t}>{t}</option>)}
                      </select>
                      
                      <select 
                        value={chartConfigs[i].x} 
                        onChange={e => {
                          const newConf = [...chartConfigs];
                          newConf[i].x = e.target.value;
                          setChartConfigs(newConf);
                        }}
                        className="w-full border-[2px] border-black p-1.5 font-bold uppercase text-[10px]"
                      >
                        <option value="">- X AXIS -</option>
                        {modalColumns.map(c => <option key={c.name} value={c.name}>{c.name}</option>)}
                      </select>

                      <select 
                        value={chartConfigs[i].y} 
                        onChange={e => {
                          const newConf = [...chartConfigs];
                          newConf[i].y = e.target.value;
                          setChartConfigs(newConf);
                        }}
                        className="w-full border-[2px] border-black p-1.5 font-bold uppercase text-[10px]"
                      >
                        <option value="">- Y AXIS -</option>
                        {modalColumns.map(c => <option key={c.name} value={c.name}>{c.name}</option>)}
                      </select>
                    </div>
                  )})}
                </div>
              </section>

              {/* STEP 4 */}
              <section className="space-y-3 pb-8">
                <h4 className="font-black text-sm uppercase">STEP 4 — DASHBOARD TITLE</h4>
                <input 
                  type="text" 
                  value={dashTitle} 
                  onChange={(e) => setDashTitle(e.target.value)}
                  className="w-full border-[3px] border-black p-3 font-bold uppercase focus:outline-none focus:bg-[#fff5ba]"
                  placeholder="MY DASHBOARD"
                />
              </section>

            </div>

            <div className="p-4 border-t-[3px] border-black bg-white flex justify-end gap-4 shrink-0">
              <button 
                onClick={() => setShowModal(false)}
                className="px-6 py-2 border-[2px] border-black font-black uppercase text-sm hover:bg-gray-100"
              >
                CANCEL
              </button>
              <button 
                onClick={handleGenerate}
                className="px-8 py-2 bg-[#ffe45e] border-[3px] border-black font-black uppercase text-sm shadow-[4px_4px_0px_#000] hover:-translate-y-1 hover:-translate-x-1 active:translate-x-0 active:translate-y-0 active:shadow-none transition-all"
              >
                GENERATE
              </button>
            </div>

          </div>
        </div>
      )}
    </div>
  );
};

export default DashboardToolbox;
