import React, { useState, useEffect } from 'react';
import { Trash2, Save } from 'lucide-react';
import DashboardToolbox from './DashboardToolbox';
import DashboardProperties from './DashboardProperties';
import CanvasWidgetWrapper from './widgets/CanvasWidgetWrapper';
import HeadingWidget from './widgets/HeadingWidget';
import MetricWidget from './widgets/MetricWidget';
import ChartWidget from './widgets/ChartWidget';
import { getFeaturesInfo } from '../../api/client';

const DashboardCanvas = ({ isDataLoaded }) => {
  const [widgets, setWidgets] = useState([]);
  const [selectedId, setSelectedId] = useState(null);
  const [columns, setColumns] = useState([]);

  useEffect(() => {
    if (isDataLoaded) fetchCols();
  }, [isDataLoaded]);

  const fetchCols = async () => {
    try {
      const data = await getFeaturesInfo();
      setColumns(data.columns || []);
    } catch (e) {
      console.error(e);
    }
  };

  const addWidget = (type) => {
    let width, height;
    let config = {};

    if (type === 'heading') {
      width = 400; height = 80;
      config = { text: 'DASHBOARD TITLE', size: 'LARGE', align: 'LEFT' };
    } else if (type === 'metric') {
      width = 220; height = 140;
      config = { column: '', aggregation: 'SUM', label: '', color: '#ffe45e' };
    } else if (type === 'chart') {
      width = 450; height = 320;
      config = { chart_type: 'BAR', x_column: '', y_column: '', aggregation: 'MEAN', title: '', theme: 'BRUTAL', showLegend: true, showGrid: true };
    }

    // Stack them vaguely in the center by default, offset slightly based on existing widgets to prevent exact overlap
    const offset = (widgets.length % 5) * 24;
    
    const newWidget = {
      id: Date.now(),
      type,
      x: 100 + offset,
      y: 100 + offset,
      width,
      height,
      config
    };

    setWidgets([...widgets, newWidget]);
    setSelectedId(newWidget.id);
  };

  const updateWidget = (id, updates) => {
    setWidgets(widgets.map(w => w.id === id ? { ...w, ...updates } : w));
  };

  const removeWidget = (id) => {
    setWidgets(widgets.filter(w => w.id !== id));
    if (selectedId === id) setSelectedId(null);
  };

  const clearCanvas = () => {
    if (window.confirm("Are you sure you want to clear the canvas?")) {
      setWidgets([]);
      setSelectedId(null);
    }
  };

  const autoGenerateDashboard = (template, title, metricConfigs, chartConfigs) => {
    // Basic auto-arrange logic
    const newWidgets = [];
    let currentY = 48;

    // 1. Heading
    if (title) {
      newWidgets.push({
        id: Date.now() + 1, type: 'heading',
        x: 48, y: currentY, width: 800, height: 80,
        config: { text: title, size: 'HUGE', align: 'LEFT' }
      });
      currentY += 104;
    }

    // 2. Metrics (Horizontal row)
    let metricCount = 3;
    if (template === 'OVERVIEW') metricCount = 3;
    else if (template === 'DEEP_DIVE') metricCount = 4;
    else if (template === 'COMPARISON') metricCount = 2;

    for (let i = 0; i < metricCount; i++) {
      newWidgets.push({
        id: Date.now() + 10 + i, type: 'metric',
        x: 48 + (i * 240), y: currentY, width: 220, height: 140,
        config: { 
          column: metricConfigs[i]?.col || '', 
          aggregation: metricConfigs[i]?.agg || 'SUM', 
          color: ['#ffe45e', '#00f0ff', '#ff499e', '#ff8c00'][i%4] 
        }
      });
    }
    if (metricCount > 0) currentY += 164;

    // 3. Charts
    let chartCount = 2;
    if (template === 'OVERVIEW') chartCount = 2;
    else if (template === 'DEEP_DIVE') chartCount = 1;
    else if (template === 'COMPARISON') chartCount = 3;

    for (let i = 0; i < chartCount; i++) {
      const isSecondRow = i >= 2;
      newWidgets.push({
        id: Date.now() + 100 + i, type: 'chart',
        x: 48 + ((i % 2) * 480), y: currentY + (isSecondRow ? 344 : 0), width: 450, height: 320,
        config: { 
          chart_type: chartConfigs[i]?.type || 'BAR', 
          x_column: chartConfigs[i]?.x || '', 
          y_column: chartConfigs[i]?.y || '', 
          aggregation: chartConfigs[i]?.agg || 'MEAN', 
          theme: ['BRUTAL', 'NEON', 'WARM', 'MONO'][i%4] 
        }
      });
    }

    setWidgets(newWidgets);
    setSelectedId(null);
  };

  const selectedWidget = widgets.find(w => w.id === selectedId);

  return (
    <div className="flex w-full h-[calc(100vh-160px)]">
      
      {/* LEFT: TOOLBOX */}
      <DashboardToolbox 
        addWidget={addWidget} 
        autoGenerateDashboard={autoGenerateDashboard} 
        columns={columns} 
      />

      {/* MIDDLE: CANVAS */}
      <div className="flex-1 flex flex-col min-w-0 bg-[#fef9ef] relative">
        
        {/* Canvas Toolbar */}
        <div className="h-[48px] bg-[#fef9ef] border-b-[2px] border-black flex items-center justify-between px-4 shrink-0 z-10">
          <div className="flex gap-2">
            <button 
              onClick={clearCanvas}
              className="px-3 py-1.5 border-[2px] border-black bg-white hover:bg-[#ff499e] hover:text-white transition-colors flex items-center gap-2 font-black uppercase text-xs"
            >
              <Trash2 size={14} /> Clear Canvas
            </button>
            <button 
              className="px-3 py-1.5 border-[2px] border-black bg-[#ffe45e] hover:bg-yellow-500 transition-colors flex items-center gap-2 font-black uppercase text-xs"
              onClick={() => alert("Dashboard saved to workspace (simulated)")}
            >
              <Save size={14} /> Save Layout
            </button>
          </div>
          <div className="font-black text-[10px] uppercase bg-black text-white px-2 py-1">
            {widgets.length} WIDGETS
          </div>
        </div>

        {/* Canvas Area with Dot Grid */}
        <div 
          className="flex-1 overflow-auto relative"
          onClick={() => setSelectedId(null)}
          style={{
            backgroundImage: 'radial-gradient(#00000015 2px, transparent 2px)',
            backgroundSize: '24px 24px'
          }}
        >
          {!isDataLoaded && (
            <div className="absolute inset-0 flex items-center justify-center pointer-events-none">
              <span className="font-black text-2xl uppercase opacity-20 text-black">NO DATA LOADED</span>
            </div>
          )}
          
          <div className="relative min-w-[1200px] min-h-[1200px]">
            {widgets.map(widget => (
              <CanvasWidgetWrapper
                key={widget.id}
                widget={widget}
                updateWidget={updateWidget}
                removeWidget={removeWidget}
                selectWidget={setSelectedId}
                isSelected={selectedId === widget.id}
              >
                {widget.type === 'heading' && <HeadingWidget widget={widget} updateWidget={updateWidget} />}
                {widget.type === 'metric' && <MetricWidget widget={widget} />}
                {widget.type === 'chart' && <ChartWidget widget={widget} />}
              </CanvasWidgetWrapper>
            ))}
          </div>
        </div>

      </div>

      {/* RIGHT: PROPERTIES */}
      <DashboardProperties 
        selectedWidget={selectedWidget} 
        updateWidget={updateWidget} 
        deselectWidget={() => setSelectedId(null)}
        columns={columns}
      />

    </div>
  );
};

export default DashboardCanvas;
